### ISSUE TITLE
CASA 5.6 introduces NaNs into the model 

### ISSUE THREAD

**Issue by toshikisaito1005** [akleroy/phangs_imaging_scripts#124]
tclean with CASA 5.6 gave a lot of NaN pixels in many channels of .image and .model products, which affect, for example, imstat output, so that we cannot properly estimate the total flux of clean model cubes.

Currently, we know this happens
(1) when CASA 5.6.1,
(2) when deconvolver="multiscale",
(3) when niter > 0, and
(4) when all channels are selected.

(2) and (3) are inevitable to create products.  In order to avoid this, do not use flagged/masked channels (typically edge channels) in ms files, or running handlerImaging with the previous CASA versions.

P.S. I am getting in touch with the ALMA helpdesk.

**Comment by akleroy** [comment]
Patched with Eric K's fix. Dumb that this is still a thing.
