### ISSUE TITLE
CASA 6.1 compatibility

### ISSUE THREAD

**Issue by low-sky** [akleroy/phangs_imaging_scripts#168]
Just a list of things to amend or change to make this work for 6.1

- [ ] `from importlib import reload`
- [ ] `casa_enabled` has `endswith('start_casa.py')`
- [ ] `dict_keys.sort()` -> `sorted(dict_keys)`

Add 'em as you get 'em

**Comment by e-koch** [comment]
Yes, runs in CASA 6.x are now working.

There may be corner cases but we should make new issues in that case.
