### ISSUE TITLE
Punch list for noise, masks, and derived products after initial QA

### ISSUE THREAD

**Issue by low-sky** [akleroy/phangs_imaging_scripts#175]
Issues to be dealt with

- [ ] Create moment 0 incorporating upper limits
- [ ] Tpeak maps with velocity slab masking instead of signal masking
- [ ] Allow for external masking (e.g., for C18O)
- [ ] Spectral response of noise needs to be deal with missing channels smoothly
- [ ] Noise estimate at edge of cube is under-estimated because of beam roll-off leading to an excess of mask 
- [ ] Create coverage maps from coverage cubes
- [ ] Check noise for tpeak12p5 maps and potentially add a sqrt(N) scaling to the noise before propagation.
- [ ] Add OBJECT field to all maps
- [ ] Add DATAMIN/DATAMAX to the header for all products
- [ ] Cast down to BITPIX = -32 (products) or +8 (masks)

**Comment by akleroy** [comment]
@low-sky review and close or decide to leave open?
