### ISSUE TITLE
How to bin the staged continnuum .ms file to a certain channel width with phangs pipeline? 

### ISSUE THREAD

**Issue by heh15** [akleroy/phangs_imaging_scripts#181]
I was trying to use phangs pipeline to produce the continuum image. While I was staging the data, I found `this_uvh.loop_stage_uvdata()` method will either collapse each spectral window in the continuum measurement set into a single channel or not bin the channels at all. I would like channels to be binned to a certain width so the script can run faster in imaging steps while the continuum products not suffering from the bandwidth smearing. I was wondering if there is an easy way to set it in the phangs pipeline.

**Comment by astrojysun** [comment]
In case you have not found a work-around for this: I am currently working on improving the continuum extraction scheme to do exactly this. I am happy to follow up with you once I finish testing the code and submit a pull request.

**Comment by astrojysun** [comment]
The new code is described in #210.

**Comment by thomaswilliamsastro** [comment]
Closing this since it's merged in #214
