### ISSUE TITLE
Masking not working properly for continuum imaging

### ISSUE THREAD

**Issue by heh15** [akleroy/phangs_imaging_scripts#183]
I was trying to make cotinuum image using PHANGS pipeline. After it's done, I checked '.mask' file of the imaging product. It seems all of the '.mask' files mask the entire field of view. This is not the case for CO imaging as the mask from that clearly traces where the emission is.  Here is my imaging command: 

```
this_imh.loop_imaging(\
        do_dirty_image = True,
        do_revert_to_dirty = False,
        do_read_clean_mask = False,
        do_multiscale_clean = True,
        do_revert_to_multiscale = False,
        do_singlescale_mask = True,
        do_singlescale_clean = True,
        do_export_to_fits = True,
        extra_ext_in = '',
        extra_ext_out = '',
        )
```
I was wondering if this is an issue of PHANGS pipeline or it's because I didn't set some thing right.

**Comment by akleroy** [comment]
Addressed and merged. Thanks @1054
