### ISSUE TITLE
Check that cube frequency range is completely covered by all input Measurement Sets

### ISSUE THREAD

**Issue by thomaswilliamsastro** [akleroy/phangs_imaging_scripts#190]
Because CASA cleans with a common beam, if the selected velocity range is covered by some input MSs but not others, the common beam size is messed up. This is particularly an issue where the 12m data doesn't cover quite the same frequency range as the 7m, leading to a ~5arcsec beam. I think this check should probably be at the MSTransform stage?

EDIT:

Alternatively, changing 

`restoringbeam =  "common"`

to

`restoringbeam =  "` 

in continuum_mosaic.clean may clean with a Gaussian fitted separately to each image plane

**Comment by akleroy** [comment]
Addressed and merged.
