### ISSUE TITLE
Add support for Hydrogen RRL lines

### ISSUE THREAD

**Issue by astrojysun** [akleroy/phangs_imaging_scripts#209]
Would it make sense to add a list of Hydrogen RRL lines in `utilsLines.py`? Currently the pipeline does not support the imaging of these lines in the same way as the (brighter) molecular lines.

**Comment by low-sky** [comment]
I think so.  Want to PR them in?

**Comment by akleroy** [comment]
Definitely! They are only not in from laziness - also make a line family
for them?

**Comment by astrojysun** [comment]
Done -- see #210

**Comment by thomaswilliamsastro** [comment]
Merged in #214 , closing this
